const books = [
{"id":1,"title":"Os Maias","author":"Eça de Queirós"},
{"id":2,"title":"O Primo Basílio","author":"Eça de Queirós"},
{"id":3,"title":"Ensaio Sobre a Cegueira","author":"José Saramago"},
{"id":4,"title":"O Ano da Morte de Ricardo Reis","author":"José Saramago"},
{"id":5,"title":"Mensagem","author":"Fernando Pessoa"},
{"id":6,"title":"O Livro do Desassossego","author":"Fernando Pessoa"},
{"id":7,"title":"Os Lusíadas","author":"Luís de Camões"},
{"id":8,"title":"Amor de Perdição","author":"Camilo Castelo Branco"},
{"id":9,"title":"O Mandarim","author":"Eça de Queirós"},
{"id":10,"title":"Viagens na Minha Terra","author":"Almeida Garrett"},
{"id":11,"title":"A Cidade e as Serras","author":"Eça de Queirós"},
{"id":12,"title":"A Ilustre Casa de Ramires","author":"Eça de Queirós"},
{"id":13,"title":"Memorial do Convento","author":"José Saramago"},
{"id":14,"title":"A Jangada de Pedra","author":"José Saramago"},
{"id":15,"title":"Levantado do Chão","author":"José Saramago"},
{"id":16,"title":"Poesias de Álvaro de Campos","author":"Fernando Pessoa"},
{"id":17,"title":"O Guardador de Rebanhos","author":"Fernando Pessoa"},
{"id":18,"title":"Eurico, o Presbítero","author":"Alexandre Herculano"},
{"id":19,"title":"A Relíquia","author":"Eça de Queirós"},
{"id":20,"title":"Os Transparentes","author":"Ondjaki"},
{"id":21,"title":"O Retorno","author":"Dulce Maria Cardoso"},
{"id":22,"title":"Nação Crioula","author":"José Eduardo Agualusa"},
{"id":23,"title":"O Delfim","author":"José Cardoso Pires"},
{"id":24,"title":"A Sibila","author":"Agustina Bessa-Luís"},
{"id":25,"title":"Vale Abraão","author":"Agustina Bessa-Luís"},
{"id":26,"title":"Aparição","author":"Vergílio Ferreira"},
{"id":27,"title":"Amor de Salvação","author":"Camilo Castelo Branco"},
{"id":28,"title":"Esteiros","author":"Soeiro Pereira Gomes"},
{"id":29,"title":"O Físico Prodigioso","author":"Jorge de Sena"},
{"id":30,"title":"Uma Abelha na Chuva","author":"Carlos de Oliveira"},
{"id":31,"title":"Sinais de Fogo","author":"Jorge de Sena"},
{"id":32,"title":"O Barão","author":"Branquinho da Fonseca"},
{"id":33,"title":"Lillias Fraser","author":"Hélia Correia"},
{"id":34,"title":"A Costa dos Murmúrios","author":"Lídia Jorge"},
{"id":35,"title":"Os Pilares da Terra","author":"Ken Follett"},
{"id":36,"title":"A Boneca de Kokoschka","author":"António Lobo Antunes"},
{"id":37,"title":"Os Cus de Judas","author":"António Lobo Antunes"},
{"id":38,"title":"O Homem que Matou o Diabo","author":"Alexandre Herculano"},
{"id":39,"title":"O Vendedor de Passados","author":"José Eduardo Agualusa"},
{"id":40,"title":"Alentejo, Alentejo","author":"José Saramago"},
{"id":41,"title":"Os Imortais","author":"Sophia de Mello Breyner"},
{"id":42,"title":"A Noite","author":"Sophia de Mello Breyner"},
{"id":43,"title":"A Solução Final","author":"António Lobo Antunes"},
{"id":44,"title":"A Janela","author":"Mia Couto"},
{"id":45,"title":"Terra Sonâmbula","author":"Mia Couto"},
{"id":46,"title":"A Bagagem do Viajante","author":"Lídia Jorge"},
{"id":47,"title":"Enquanto Eu Era Viajante","author":"A. de Andrade"},
{"id":48,"title":"A Máquina de Fazer Espanhóis","author":"Valter Hugo Mãe"},
{"id":49,"title":"Livro do Desassossego (seleção)","author":"Fernando Pessoa"},
{"id":50,"title":"Contos","author":"Camilo Castelo Branco"},
{"id":51,"title":"Romanceiro da Inconfidência","author":"Cecília Meireles"},
{"id":52,"title":"O Homem do Princípio","author":"Gonçalo M. Tavares"},
{"id":53,"title":"Mais Cinco","author":"José Cardoso Pires"},
{"id":54,"title":"Livro do Desassossego (Bernardo Soares)","author":"Fernando Pessoa"},
{"id":55,"title":"O Olhar do Outro","author":"Ana Teresa Pereira"}
];
